### PR TITLE
Add obs4MIPs and input4MIPs projects

### PR DESCRIPTION
**Pull request by mauzey1**
Adds obs4MIPs and input4MIPs as projects publications can list along with lists of models used by each of them.

### CODE REVIEW

**Comment by durack1** [comment]
@mauzey1 good question, the dots seems obsolete, so yes I agree remove them if possible

**Comment by durack1** [comment]
@mauzey1 ping me again when you want signoff - I'll pre-approve the PR just so I am not in your way

**Review by durack1 — APPROVED** [review]
@mauzey1 looks like good progress to me - I might ping @gleckler1 and @taylor13 just so we're all in the loop with progress

**Comment by mauzey1** [comment]
The list of models without the bullet points.

Screenshot 2023-07-11 at 16-28-21 Advanced Search
Screenshot 2023-07-11 at 16-41-29 Advanced Search

**Comment by taylor13** [comment]
Instead of labeling the list "Model", we should label it "Source" because that more generally applies to input4MIPs and obs4MIPs as well as CMIP.

**Comment by mauzey1** [comment]
@durack1 @taylor13 

Do we want to relabel "model" to "source" in PubHub?  This will require extensive changes beyond this pull request.

**Comment by taylor13** [comment]
I don't think this is a PubHub change, just a change to our input to PubHub.  I saw that in your screenshot above there were headings on each of the lists like "Activity", "Experiment", "Frequency", etc., and I assumed that the heading that's hidden was "Model".  If it is, it should probably be changed to "Source", which is more appropriate for input4MIPs and obs4MIPs.  Maybe it already says "Source" in which case no action would be required.   If this is difficult, don't bother, of course.

**Comment by mauzey1** [comment]
The term 'model' is used throughout the website including the heading of the models/sources list in the above images.  The code of the site and its database also refer to them as models.  We could try changing all of the user-facing labels from 'model' to 'source' but retain the use of the term 'model' internally.

Changing only the input heading to 'source' might cause confusion for users since the source values would appear under the label 'model' when browsing the viewing page.

**Comment by taylor13** [comment]
Thanks for explaining this.  Let's think about it further then before possibly making any changes.

**Comment by durack1** [comment]
Thanks for this @mauzey1 it is indeed a more in-depth change than was originally assumed. The logic in renaming the sources "source_id" in CMIP6 was that this can identify not just a model contribution, but also an observational contribution which doesn't most often include a model. So as we are now expanding the site to deal with data across not only the CMIP/model phases, but also the observational products, this model -> source change does make sense.

I agree, if this change occurs it will need to be represented on all the outward facing pages. I don't have a strong feeling for the internals which folks don't see

**Comment by mauzey1** [comment]
@durack1 @taylor13 
I've now changed the labels for models/sources to be 'Source' on the site.

Screenshot 2023-07-17 at 11-43-28 edit
Screenshot 2023-07-17 at 12-01-36 Publication Hub

**Comment by taylor13** [comment]
Very nice!  Thanks for that.
Karl

From: mauzey1 ***@***.***>
Reply-To: aims-group/publication-site ***@***.***>
Date: Monday, July 17, 2023 at 12:06 PM
To: aims-group/publication-site ***@***.***>
Cc: "Taylor, Karl E." ***@***.***>, Mention ***@***.***>
Subject: Re: [aims-group/publication-site] Add obs4MIPs and input4MIPs projects (PR #187)


@durack1<https://urldefense.us/v3/__https:/github.com/durack1__;!!G2kpM7uM-TzIFchu!x4lkSeQLShYCffRqRZFONrODiXfoSekwMSf_D32OHbcU9E3UPDNDnOqRsQqaXekqjswAOe4vG_8Z0KkEBjcXHQbmZjs$> @taylor13<https://urldefense.us/v3/__https:/github.com/taylor13__;!!G2kpM7uM-TzIFchu!x4lkSeQLShYCffRqRZFONrODiXfoSekwMSf_D32OHbcU9E3UPDNDnOqRsQqaXekqjswAOe4vG_8Z0KkEBjcXl4fvP1Q$>
I've now changed the labels for models/sources to be 'Source' on the site.

[Screenshot 2023-07-17 at 11-43-28 edit]<https://urldefense.us/v3/__https:/user-images.githubusercontent.com/42009431/254043934-6a5c8726-5977-43d4-83d8-f786826778b9.png__;!!G2kpM7uM-TzIFchu!x4lkSeQLShYCffRqRZFONrODiXfoSekwMSf_D32OHbcU9E3UPDNDnOqRsQqaXekqjswAOe4vG_8Z0KkEBjcXmykcPjI$>
[Screenshot 2023-07-17 at 12-01-36 Publication Hub]<https://urldefense.us/v3/__https:/user-images.githubusercontent.com/42009431/254043968-9328eba4-359c-4076-b2d6-528b986cdfd5.png__;!!G2kpM7uM-TzIFchu!x4lkSeQLShYCffRqRZFONrODiXfoSekwMSf_D32OHbcU9E3UPDNDnOqRsQqaXekqjswAOe4vG_8Z0KkEBjcXzL4Yomc$>

**Comment by durack1** [comment]
Agreed @mauzey1 great, please merge and get this into operation!

**Comment by mauzey1** [comment]
@durack1 @taylor13  Changes are now live.

**Comment by durack1** [comment]
@mauzey1 excellent - I just took a peek at https://cmip-publications.llnl.gov/ and it seems that "Models" is still showing up under the "More Info" expansion, see below
Screen Shot 2023-07-17 at 2 52 30 PM

**Comment by mauzey1** [comment]
You might need to clear your browser's cache.

**Comment by durack1** [comment]
@mauzey1 yep, you're right - if I use Safari (which I never use):
Screen Shot 2023-07-17 at 2 55 03 PM

**Pull request merged**
