### PR TITLE
Move documentation from gh-pages to master/docs

### PR DESCRIPTION
**Pull request by mauzey1**
Move the files for the documentation site from `gh-pages` branch to the docs directory in the `master` branch.  This will make it easier to add documentation changes along side code changes.

This PR will also add changes to the docs
- Replace Python 2.7 with Python 3
- Fix vitrualenv link
- Add `python manage.py collectstatic` step to installation instructions
- Update publication-site version from 0.2.0 to 0.3.0
- Change author from James Crean to Chris Mauzey

The current copyright info is `© Copyright 2017, James Crean.`.  Should this be changed?  What should it be changed to?  Do we even need copyright info?

### CODE REVIEW

**Comment by nathanlcarlson** [comment]
For the copyright issue, you could probably just remove it.

**Comment by taylor13** [comment]
I agree about the copyright issue.

**Comment by mauzey1** [comment]
I have removed the copyright.  Here's what the site looks like now.
https://mauzey1.github.io/publication-site/html/index.html

**Comment by durack1** [comment]
@mauzey1 just taking a look at this, is there a need for 3 versions of `jquery`, you have
```
docs/html/_static/jquery-3.1.0.js
 docs/html/_static/jquery-3.2.1.js
 docs/html/_static/jquery-3.5.1.js
```
I've been pinged on old dependencies across a repo a couple of weeks back, so might be a good idea to point them at 3.5.1 (released 4 May 2020, and is the latest) alone? Another options is to use the slim build variant (https://jquery.com/download/) which cuts down repo sizes

**Pull request merged**
